---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/part-of: infrastructure
  namespace: ingress-nginx

resources:
  - namespace.yaml
  - helmrelease.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: ingress-nginx
      managed-by: flux
      tier: infrastructure

commonAnnotations:
  note: "Nginx Ingress Controller deployed via GitOps"
  coexists-with: "traefik"