apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - externalsecrets-role.yaml
  - tf-minio-externalsecret.yaml
  - externalsecrets-rolebinding.yaml
